//
//  HomePresenter.swift
//  NEWSVIPERUIKIT
//
//  Created by Halil İbrahim Öztekin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentPrepareDataSource(articles: [Home.News.Article]?)
    func presentDetailPage()
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
    func presentPrepareDataSource(articles: [Home.News.Article]?) {
        self.viewController?.displayPrepareCollectionView(articles: articles)
    }
    
    func presentDetailPage() {
        
    }
  
  
}
