//
//  HomeModels.swift
//  NEWSVIPERUIKIT
//
//  Created by Halil İbrahim Öztekin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    
    enum News
    {
        // MARK: - News
        struct Response: Codable {
            var articles: [Article]?
        }
        
        // MARK: - Article
        struct Article: Codable {
            let source: Source?
            let author: String?
            let title: String?
            let description: String?
            let url: String?
            let urlToImage: String?
            let publishedAt: String?
            let content: String?
        }
        
        // MARK: - Source
        struct Source: Codable {
            let id: String?
            let name: String?
        }
    }
}
